### ISSUE TITLE
Location for the automatic backup?

### ISSUE THREAD

**Issue by sphh** [3zpnix/WriteOn#17]
When I enable `Automatic Backup`, I see the notice `Backup successful`. Where is that backup saved? I haven't set any place where to save the backup … (and haven't given any permission to save and read the SD card)

**Comment by 3zpnix** [comment]
I'm still working around that part, so it might not work completely. I haven't had set an option for it to add a save location just yet.

**Comment by sphh** [comment]
So where can the automatic backup be found?

**Comment by 3zpnix** [comment]
It's currently within but outside the root folder, it can't be accessible for now. I'll probably release a fix for that in v2.0

**Comment by sphh** [comment]
To sync the notes, e.g. with [Syncthing](https://syncthing.net/), I would love to have the following settings:
1. Location of the backup
2. Either zipped or unzipped (plain text) backup
3. Backup interval:
    1. Fixed interval, e.g. daily, hourly
    2. When a not has changed, e.g. when switching from `edit` to `view` mode or when returning to the main screen
4. Load the backup, when it has changed

Is that possible?

**Comment by 3zpnix** [comment]
Yes, those would be possible. Won't syncing on interval increase a little bit of battery usage though? I'm trying to make a notes app that doesn't really take much battery.

**Comment by sphh** [comment]
The interval backup only came into play, because that is what it is now.

Syncing always increase the battery usage. That's what you have to pay, if you want to stay synced. But IMHO exporting/backing up, when leaving the edit screen or returning to the main screen would be the better option. Everything else is up to the sync software.

**Comment by 3zpnix** [comment]
Alright, I'll think about it. Thanks for the suggestions.

**Comment by 3zpnix** [comment]
I have fixed the location for the automatic backup feature, previously it was in the android data folder but now you can set it to where you want it to be. I'll release this fix together with the upcoming v1.2 soon. Thank you again for the bug report <3
